services:

  backend:
    image: ghcr.io/m0wer/landing_generator:master
    container_name: landing-generator
    build:
      context: .
    environment:
      ROOT_PATH: "/api"
      MAX_WORKERS: ${MAX_WORKERS:-1}
      LOGURU_LEVEL: ${LOGURU_LEVEL:-INFO}
      ADMIN_SECRET: ${ADMIN_SECRET:-admin}
    volumes:
      - ${DATA_PATH:-./data/}:/app/data/
      - ${CONF_PATH:-./conf/}:/app/conf/
    ports:
      - ${WEB_PORT:-8000}:80
    restart: unless-stopped
    user: ${DOCKER_USER:-1000:1000}
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.timetracking.entrypoints=websecure
      - traefik.http.routers.timetracking.rule=Host(`$DOMAIN`)
      - traefik.http.routers.timetracking.tls=true
      - traefik.http.routers.timetracking.tls.certresolver=le
      - com.centurylinklabs.watchtower.enable=false
networks:
  timetracking:
  traefik:
    name: ${TRAEFIK_NETWORK}
    external: true   
